---
- name: Apache install & start services
  hosts: all
  become: true

  tasks:
  - name: install Apache
    yum:
      name: httpd
      state: latest

  - name: start Apache
    service:
      name: httpd
      state: started